/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const TenantId = IDL.Nat;
export const BillingId = IDL.Nat;
export const Timestamp = IDL.Int;
export const InvoiceRecord = IDL.Record({
  'paid' : IDL.Bool,
  'invoiceId' : IDL.Nat,
  'issuedAt' : Timestamp,
  'amount' : IDL.Nat,
});
export const PlanTier = IDL.Variant({
  'growth' : IDL.Null,
  'enterprise' : IDL.Null,
  'starter' : IDL.Null,
  'scale' : IDL.Null,
});
export const Billing = IDL.Record({
  'id' : BillingId,
  'includedMinutes' : IDL.Nat,
  'invoiceHistory' : IDL.Vec(InvoiceRecord),
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'planTier' : PlanTier,
  'usedMinutes' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeadStatus = IDL.Variant({
  'aiContacted' : IDL.Null,
  'liveTransferred' : IDL.Null,
  'sold' : IDL.Null,
  'apptBooked' : IDL.Null,
  'newLead' : IDL.Null,
});
export const LeadSource = IDL.Variant({
  'referral' : IDL.Null,
  'voiceCampaign' : IDL.Null,
  'webForm' : IDL.Null,
  'smsCampaign' : IDL.Null,
  'aiDialer' : IDL.Null,
  'csvImport' : IDL.Null,
  'inbound' : IDL.Null,
  'outbound' : IDL.Null,
});
export const UserId = IDL.Nat;
export const BulkLeadInput = IDL.Record({
  'status' : IDL.Opt(LeadStatus),
  'source' : IDL.Opt(LeadSource),
  'name' : IDL.Text,
  'assignedAgentId' : IDL.Opt(UserId),
  'email' : IDL.Opt(IDL.Text),
  'annualPremiumValue' : IDL.Opt(IDL.Nat),
  'phone' : IDL.Text,
});
export const BulkImportResult = IDL.Record({
  'errors' : IDL.Vec(IDL.Text),
  'createdIds' : IDL.Vec(IDL.Nat),
});
export const LeadId = IDL.Nat;
export const InteractionType = IDL.Variant({
  'liveTransfer' : IDL.Null,
  'appointmentBooking' : IDL.Null,
  'textMessage' : IDL.Null,
  'voiceCall' : IDL.Null,
});
export const InteractionOutcome = IDL.Variant({
  'noAnswer' : IDL.Null,
  'sent' : IDL.Null,
  'booked' : IDL.Null,
  'transferred' : IDL.Null,
  'replied' : IDL.Null,
  'delivered' : IDL.Null,
  'failed' : IDL.Null,
  'qualified' : IDL.Null,
});
export const InteractionId = IDL.Nat;
export const VoiceCallStatus = IDL.Variant({
  'initiated' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const VoiceCallDetail = IDL.Record({
  'status' : VoiceCallStatus,
  'duration' : IDL.Nat,
  'callId' : IDL.Text,
});
export const AiInteraction = IDL.Record({
  'id' : InteractionId,
  'interactionType' : InteractionType,
  'minutesSaved' : IDL.Nat,
  'createdAt' : Timestamp,
  'agentId' : IDL.Opt(UserId),
  'tenantId' : TenantId,
  'summary' : IDL.Text,
  'leadId' : LeadId,
  'durationSeconds' : IDL.Nat,
  'outcome' : InteractionOutcome,
  'voiceCall' : IDL.Opt(VoiceCallDetail),
});
export const Lead = IDL.Record({
  'id' : LeadId,
  'status' : LeadStatus,
  'source' : LeadSource,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'assignedAgentId' : IDL.Opt(UserId),
  'email' : IDL.Text,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'annualPremiumValue' : IDL.Nat,
  'phone' : IDL.Text,
});
export const AudienceSegment = IDL.Variant({
  'aiContacted' : IDL.Null,
  'liveTransferred' : IDL.Null,
  'sold' : IDL.Null,
  'allLeads' : IDL.Null,
  'newLeads' : IDL.Null,
  'apptBooked' : IDL.Null,
});
export const CampaignId = IDL.Nat;
export const CampaignStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'completed' : IDL.Null,
  'draft' : IDL.Null,
  'running' : IDL.Null,
  'archived' : IDL.Null,
  'paused' : IDL.Null,
});
export const SmsCampaign = IDL.Record({
  'id' : CampaignId,
  'status' : CampaignStatus,
  'messageTemplate' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'sentCount' : IDL.Nat,
  'tenantId' : TenantId,
  'audienceSegment' : AudienceSegment,
  'responseCount' : IDL.Nat,
});
export const VoiceAgentConfig = IDL.Record({
  'model' : IDL.Text,
  'voiceProvider' : IDL.Text,
  'voiceId' : IDL.Text,
  'agentName' : IDL.Text,
  'language' : IDL.Text,
  'voiceSettings' : IDL.Text,
  'apiKey' : IDL.Text,
  'transferPhoneNumber' : IDL.Text,
});
export const Tenant = IDL.Record({
  'id' : TenantId,
  'createdAt' : Timestamp,
  'agencyName' : IDL.Text,
  'voiceAgent' : VoiceAgentConfig,
  'primaryContact' : IDL.Text,
  'planTier' : PlanTier,
});
export const Role = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'agent' : IDL.Null,
});
export const UserStatus = IDL.Variant({
  'away' : IDL.Null,
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : IDL.Text,
  'tenantId' : TenantId,
});
export const VoiceCampaign = IDL.Record({
  'id' : CampaignId,
  'status' : CampaignStatus,
  'minutesSaved' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'voiceAgent' : VoiceAgentConfig,
  'qualifiedTransfers' : IDL.Nat,
  'targetStatus' : LeadStatus,
  'targetSegment' : AudienceSegment,
  'callsPlaced' : IDL.Nat,
});
export const ColumnChartMetric = IDL.Record({
  'callsAi' : IDL.Nat,
  'apptsBooked' : IDL.Nat,
  'liveTransfers' : IDL.Nat,
  'smsSent' : IDL.Nat,
  'leadsSold' : IDL.Nat,
});
export const DashboardSummary = IDL.Record({
  'activeAgentsOnline' : IDL.Nat,
  'totalAgents' : IDL.Nat,
  'timeSavedByAiMinutes' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'activeAgentsPercentage' : IDL.Float64,
});
export const LiveEventSource = IDL.Variant({
  'sys' : IDL.Null,
  'aiVoiceRouter' : IDL.Null,
  'voiceCampaign' : IDL.Null,
  'aiTextSetter' : IDL.Null,
  'smsCampaign' : IDL.Null,
  'aiDialer' : IDL.Null,
});
export const LiveEvent = IDL.Record({
  'id' : IDL.Nat,
  'source' : LiveEventSource,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'message' : IDL.Text,
});
export const VoiceCallResult = IDL.Record({
  'status' : IDL.Variant({ 'initiated' : IDL.Null, 'failed' : IDL.Null }),
  'error' : IDL.Opt(IDL.Text),
  'callId' : IDL.Text,
});
export const VoiceCallRequest = IDL.Record({
  'voiceId' : IDL.Text,
  'task' : IDL.Text,
  'tenantId' : TenantId,
  'language' : IDL.Text,
  'leadId' : LeadId,
  'transferPhoneNumber' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__state' : IDL.Func([], [IDL.Reserved], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addInvoice' : IDL.Func([TenantId, IDL.Nat], [IDL.Opt(Billing)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportLeads' : IDL.Func(
      [TenantId, IDL.Vec(BulkLeadInput)],
      [BulkImportResult],
      [],
    ),
  'createAiInteraction' : IDL.Func(
      [
        TenantId,
        LeadId,
        IDL.Opt(UserId),
        InteractionType,
        InteractionOutcome,
        IDL.Nat,
        IDL.Text,
      ],
      [AiInteraction],
      [],
    ),
  'createLead' : IDL.Func(
      [
        TenantId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        LeadSource,
        IDL.Nat,
        IDL.Opt(UserId),
      ],
      [Lead],
      [],
    ),
  'createSmsCampaign' : IDL.Func(
      [TenantId, IDL.Text, AudienceSegment, IDL.Text],
      [SmsCampaign],
      [],
    ),
  'createTenant' : IDL.Func([IDL.Text, IDL.Text, PlanTier], [Tenant], []),
  'createUser' : IDL.Func(
      [TenantId, IDL.Principal, IDL.Text, IDL.Text, Role],
      [User],
      [],
    ),
  'createVoiceCampaign' : IDL.Func(
      [TenantId, IDL.Text, AudienceSegment, LeadStatus, VoiceAgentConfig],
      [VoiceCampaign],
      [],
    ),
  'deleteAiInteraction' : IDL.Func([InteractionId], [IDL.Bool], []),
  'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
  'deleteSmsCampaign' : IDL.Func([CampaignId], [IDL.Bool], []),
  'deleteTenant' : IDL.Func([TenantId], [IDL.Bool], []),
  'deleteUser' : IDL.Func([UserId], [IDL.Bool], []),
  'deleteVoiceCampaign' : IDL.Func([CampaignId], [IDL.Bool], []),
  'getAiInteraction' : IDL.Func(
      [InteractionId],
      [IDL.Opt(AiInteraction)],
      ['query'],
    ),
  'getBilling' : IDL.Func([TenantId], [IDL.Opt(Billing)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getColumnChartMetrics' : IDL.Func(
      [TenantId],
      [ColumnChartMetric],
      ['query'],
    ),
  'getDashboardSummary' : IDL.Func([TenantId], [DashboardSummary], ['query']),
  'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
  'getLiveEventStream' : IDL.Func(
      [TenantId, IDL.Nat],
      [IDL.Vec(LiveEvent)],
      ['query'],
    ),
  'getSmsCampaign' : IDL.Func([CampaignId], [IDL.Opt(SmsCampaign)], ['query']),
  'getTenant' : IDL.Func([TenantId], [IDL.Opt(Tenant)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getVoiceCampaign' : IDL.Func(
      [CampaignId],
      [IDL.Opt(VoiceCampaign)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'launchVoiceCampaign' : IDL.Func(
      [TenantId, CampaignId],
      [IDL.Vec(VoiceCallResult)],
      [],
    ),
  'listAiInteractionsByLead' : IDL.Func(
      [LeadId],
      [IDL.Vec(AiInteraction)],
      ['query'],
    ),
  'listAiInteractionsByTenant' : IDL.Func(
      [TenantId],
      [IDL.Vec(AiInteraction)],
      ['query'],
    ),
  'listLeadsByStatus' : IDL.Func(
      [TenantId, LeadStatus],
      [IDL.Vec(Lead)],
      ['query'],
    ),
  'listLeadsByTenant' : IDL.Func([TenantId], [IDL.Vec(Lead)], ['query']),
  'listSmsCampaignsByTenant' : IDL.Func(
      [TenantId],
      [IDL.Vec(SmsCampaign)],
      ['query'],
    ),
  'listTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
  'listUsersByTenant' : IDL.Func([TenantId], [IDL.Vec(User)], ['query']),
  'listVoiceCampaignsByTenant' : IDL.Func(
      [TenantId],
      [IDL.Vec(VoiceCampaign)],
      ['query'],
    ),
  'placeVoiceCall' : IDL.Func([VoiceCallRequest], [VoiceCallResult], []),
  'recordBillingUsage' : IDL.Func([TenantId, IDL.Nat], [IDL.Opt(Billing)], []),
  'seedMockData' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAiInteraction' : IDL.Func(
      [InteractionId, InteractionOutcome, IDL.Nat, IDL.Text],
      [IDL.Opt(AiInteraction)],
      [],
    ),
  'updateBillingPlan' : IDL.Func(
      [TenantId, PlanTier, IDL.Nat],
      [IDL.Opt(Billing)],
      [],
    ),
  'updateLead' : IDL.Func(
      [
        LeadId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        LeadSource,
        IDL.Nat,
        LeadStatus,
        IDL.Opt(UserId),
      ],
      [IDL.Opt(Lead)],
      [],
    ),
  'updateSmsCampaign' : IDL.Func(
      [CampaignId, IDL.Text, CampaignStatus, AudienceSegment, IDL.Text],
      [IDL.Opt(SmsCampaign)],
      [],
    ),
  'updateTenant' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text, PlanTier, VoiceAgentConfig],
      [IDL.Opt(Tenant)],
      [],
    ),
  'updateUser' : IDL.Func(
      [UserId, IDL.Text, IDL.Text, Role, UserStatus],
      [IDL.Opt(User)],
      [],
    ),
  'updateVoiceCampaign' : IDL.Func(
      [
        CampaignId,
        IDL.Text,
        CampaignStatus,
        AudienceSegment,
        LeadStatus,
        VoiceAgentConfig,
      ],
      [IDL.Opt(VoiceCampaign)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const TenantId = IDL.Nat;
  const BillingId = IDL.Nat;
  const Timestamp = IDL.Int;
  const InvoiceRecord = IDL.Record({
    'paid' : IDL.Bool,
    'invoiceId' : IDL.Nat,
    'issuedAt' : Timestamp,
    'amount' : IDL.Nat,
  });
  const PlanTier = IDL.Variant({
    'growth' : IDL.Null,
    'enterprise' : IDL.Null,
    'starter' : IDL.Null,
    'scale' : IDL.Null,
  });
  const Billing = IDL.Record({
    'id' : BillingId,
    'includedMinutes' : IDL.Nat,
    'invoiceHistory' : IDL.Vec(InvoiceRecord),
    'tenantId' : TenantId,
    'updatedAt' : Timestamp,
    'planTier' : PlanTier,
    'usedMinutes' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeadStatus = IDL.Variant({
    'aiContacted' : IDL.Null,
    'liveTransferred' : IDL.Null,
    'sold' : IDL.Null,
    'apptBooked' : IDL.Null,
    'newLead' : IDL.Null,
  });
  const LeadSource = IDL.Variant({
    'referral' : IDL.Null,
    'voiceCampaign' : IDL.Null,
    'webForm' : IDL.Null,
    'smsCampaign' : IDL.Null,
    'aiDialer' : IDL.Null,
    'csvImport' : IDL.Null,
    'inbound' : IDL.Null,
    'outbound' : IDL.Null,
  });
  const UserId = IDL.Nat;
  const BulkLeadInput = IDL.Record({
    'status' : IDL.Opt(LeadStatus),
    'source' : IDL.Opt(LeadSource),
    'name' : IDL.Text,
    'assignedAgentId' : IDL.Opt(UserId),
    'email' : IDL.Opt(IDL.Text),
    'annualPremiumValue' : IDL.Opt(IDL.Nat),
    'phone' : IDL.Text,
  });
  const BulkImportResult = IDL.Record({
    'errors' : IDL.Vec(IDL.Text),
    'createdIds' : IDL.Vec(IDL.Nat),
  });
  const LeadId = IDL.Nat;
  const InteractionType = IDL.Variant({
    'liveTransfer' : IDL.Null,
    'appointmentBooking' : IDL.Null,
    'textMessage' : IDL.Null,
    'voiceCall' : IDL.Null,
  });
  const InteractionOutcome = IDL.Variant({
    'noAnswer' : IDL.Null,
    'sent' : IDL.Null,
    'booked' : IDL.Null,
    'transferred' : IDL.Null,
    'replied' : IDL.Null,
    'delivered' : IDL.Null,
    'failed' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const InteractionId = IDL.Nat;
  const VoiceCallStatus = IDL.Variant({
    'initiated' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const VoiceCallDetail = IDL.Record({
    'status' : VoiceCallStatus,
    'duration' : IDL.Nat,
    'callId' : IDL.Text,
  });
  const AiInteraction = IDL.Record({
    'id' : InteractionId,
    'interactionType' : InteractionType,
    'minutesSaved' : IDL.Nat,
    'createdAt' : Timestamp,
    'agentId' : IDL.Opt(UserId),
    'tenantId' : TenantId,
    'summary' : IDL.Text,
    'leadId' : LeadId,
    'durationSeconds' : IDL.Nat,
    'outcome' : InteractionOutcome,
    'voiceCall' : IDL.Opt(VoiceCallDetail),
  });
  const Lead = IDL.Record({
    'id' : LeadId,
    'status' : LeadStatus,
    'source' : LeadSource,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'assignedAgentId' : IDL.Opt(UserId),
    'email' : IDL.Text,
    'tenantId' : TenantId,
    'updatedAt' : Timestamp,
    'annualPremiumValue' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const AudienceSegment = IDL.Variant({
    'aiContacted' : IDL.Null,
    'liveTransferred' : IDL.Null,
    'sold' : IDL.Null,
    'allLeads' : IDL.Null,
    'newLeads' : IDL.Null,
    'apptBooked' : IDL.Null,
  });
  const CampaignId = IDL.Nat;
  const CampaignStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'completed' : IDL.Null,
    'draft' : IDL.Null,
    'running' : IDL.Null,
    'archived' : IDL.Null,
    'paused' : IDL.Null,
  });
  const SmsCampaign = IDL.Record({
    'id' : CampaignId,
    'status' : CampaignStatus,
    'messageTemplate' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'sentCount' : IDL.Nat,
    'tenantId' : TenantId,
    'audienceSegment' : AudienceSegment,
    'responseCount' : IDL.Nat,
  });
  const VoiceAgentConfig = IDL.Record({
    'model' : IDL.Text,
    'voiceProvider' : IDL.Text,
    'voiceId' : IDL.Text,
    'agentName' : IDL.Text,
    'language' : IDL.Text,
    'voiceSettings' : IDL.Text,
    'apiKey' : IDL.Text,
    'transferPhoneNumber' : IDL.Text,
  });
  const Tenant = IDL.Record({
    'id' : TenantId,
    'createdAt' : Timestamp,
    'agencyName' : IDL.Text,
    'voiceAgent' : VoiceAgentConfig,
    'primaryContact' : IDL.Text,
    'planTier' : PlanTier,
  });
  const Role = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'agent' : IDL.Null,
  });
  const UserStatus = IDL.Variant({
    'away' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'email' : IDL.Text,
    'tenantId' : TenantId,
  });
  const VoiceCampaign = IDL.Record({
    'id' : CampaignId,
    'status' : CampaignStatus,
    'minutesSaved' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tenantId' : TenantId,
    'voiceAgent' : VoiceAgentConfig,
    'qualifiedTransfers' : IDL.Nat,
    'targetStatus' : LeadStatus,
    'targetSegment' : AudienceSegment,
    'callsPlaced' : IDL.Nat,
  });
  const ColumnChartMetric = IDL.Record({
    'callsAi' : IDL.Nat,
    'apptsBooked' : IDL.Nat,
    'liveTransfers' : IDL.Nat,
    'smsSent' : IDL.Nat,
    'leadsSold' : IDL.Nat,
  });
  const DashboardSummary = IDL.Record({
    'activeAgentsOnline' : IDL.Nat,
    'totalAgents' : IDL.Nat,
    'timeSavedByAiMinutes' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'activeAgentsPercentage' : IDL.Float64,
  });
  const LiveEventSource = IDL.Variant({
    'sys' : IDL.Null,
    'aiVoiceRouter' : IDL.Null,
    'voiceCampaign' : IDL.Null,
    'aiTextSetter' : IDL.Null,
    'smsCampaign' : IDL.Null,
    'aiDialer' : IDL.Null,
  });
  const LiveEvent = IDL.Record({
    'id' : IDL.Nat,
    'source' : LiveEventSource,
    'createdAt' : Timestamp,
    'tenantId' : TenantId,
    'message' : IDL.Text,
  });
  const VoiceCallResult = IDL.Record({
    'status' : IDL.Variant({ 'initiated' : IDL.Null, 'failed' : IDL.Null }),
    'error' : IDL.Opt(IDL.Text),
    'callId' : IDL.Text,
  });
  const VoiceCallRequest = IDL.Record({
    'voiceId' : IDL.Text,
    'task' : IDL.Text,
    'tenantId' : TenantId,
    'language' : IDL.Text,
    'leadId' : LeadId,
    'transferPhoneNumber' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__state' : IDL.Func([], [IDL.Reserved], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addInvoice' : IDL.Func([TenantId, IDL.Nat], [IDL.Opt(Billing)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportLeads' : IDL.Func(
        [TenantId, IDL.Vec(BulkLeadInput)],
        [BulkImportResult],
        [],
      ),
    'createAiInteraction' : IDL.Func(
        [
          TenantId,
          LeadId,
          IDL.Opt(UserId),
          InteractionType,
          InteractionOutcome,
          IDL.Nat,
          IDL.Text,
        ],
        [AiInteraction],
        [],
      ),
    'createLead' : IDL.Func(
        [
          TenantId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          LeadSource,
          IDL.Nat,
          IDL.Opt(UserId),
        ],
        [Lead],
        [],
      ),
    'createSmsCampaign' : IDL.Func(
        [TenantId, IDL.Text, AudienceSegment, IDL.Text],
        [SmsCampaign],
        [],
      ),
    'createTenant' : IDL.Func([IDL.Text, IDL.Text, PlanTier], [Tenant], []),
    'createUser' : IDL.Func(
        [TenantId, IDL.Principal, IDL.Text, IDL.Text, Role],
        [User],
        [],
      ),
    'createVoiceCampaign' : IDL.Func(
        [TenantId, IDL.Text, AudienceSegment, LeadStatus, VoiceAgentConfig],
        [VoiceCampaign],
        [],
      ),
    'deleteAiInteraction' : IDL.Func([InteractionId], [IDL.Bool], []),
    'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
    'deleteSmsCampaign' : IDL.Func([CampaignId], [IDL.Bool], []),
    'deleteTenant' : IDL.Func([TenantId], [IDL.Bool], []),
    'deleteUser' : IDL.Func([UserId], [IDL.Bool], []),
    'deleteVoiceCampaign' : IDL.Func([CampaignId], [IDL.Bool], []),
    'getAiInteraction' : IDL.Func(
        [InteractionId],
        [IDL.Opt(AiInteraction)],
        ['query'],
      ),
    'getBilling' : IDL.Func([TenantId], [IDL.Opt(Billing)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getColumnChartMetrics' : IDL.Func(
        [TenantId],
        [ColumnChartMetric],
        ['query'],
      ),
    'getDashboardSummary' : IDL.Func([TenantId], [DashboardSummary], ['query']),
    'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
    'getLiveEventStream' : IDL.Func(
        [TenantId, IDL.Nat],
        [IDL.Vec(LiveEvent)],
        ['query'],
      ),
    'getSmsCampaign' : IDL.Func(
        [CampaignId],
        [IDL.Opt(SmsCampaign)],
        ['query'],
      ),
    'getTenant' : IDL.Func([TenantId], [IDL.Opt(Tenant)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getVoiceCampaign' : IDL.Func(
        [CampaignId],
        [IDL.Opt(VoiceCampaign)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'launchVoiceCampaign' : IDL.Func(
        [TenantId, CampaignId],
        [IDL.Vec(VoiceCallResult)],
        [],
      ),
    'listAiInteractionsByLead' : IDL.Func(
        [LeadId],
        [IDL.Vec(AiInteraction)],
        ['query'],
      ),
    'listAiInteractionsByTenant' : IDL.Func(
        [TenantId],
        [IDL.Vec(AiInteraction)],
        ['query'],
      ),
    'listLeadsByStatus' : IDL.Func(
        [TenantId, LeadStatus],
        [IDL.Vec(Lead)],
        ['query'],
      ),
    'listLeadsByTenant' : IDL.Func([TenantId], [IDL.Vec(Lead)], ['query']),
    'listSmsCampaignsByTenant' : IDL.Func(
        [TenantId],
        [IDL.Vec(SmsCampaign)],
        ['query'],
      ),
    'listTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
    'listUsersByTenant' : IDL.Func([TenantId], [IDL.Vec(User)], ['query']),
    'listVoiceCampaignsByTenant' : IDL.Func(
        [TenantId],
        [IDL.Vec(VoiceCampaign)],
        ['query'],
      ),
    'placeVoiceCall' : IDL.Func([VoiceCallRequest], [VoiceCallResult], []),
    'recordBillingUsage' : IDL.Func(
        [TenantId, IDL.Nat],
        [IDL.Opt(Billing)],
        [],
      ),
    'seedMockData' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAiInteraction' : IDL.Func(
        [InteractionId, InteractionOutcome, IDL.Nat, IDL.Text],
        [IDL.Opt(AiInteraction)],
        [],
      ),
    'updateBillingPlan' : IDL.Func(
        [TenantId, PlanTier, IDL.Nat],
        [IDL.Opt(Billing)],
        [],
      ),
    'updateLead' : IDL.Func(
        [
          LeadId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          LeadSource,
          IDL.Nat,
          LeadStatus,
          IDL.Opt(UserId),
        ],
        [IDL.Opt(Lead)],
        [],
      ),
    'updateSmsCampaign' : IDL.Func(
        [CampaignId, IDL.Text, CampaignStatus, AudienceSegment, IDL.Text],
        [IDL.Opt(SmsCampaign)],
        [],
      ),
    'updateTenant' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text, PlanTier, VoiceAgentConfig],
        [IDL.Opt(Tenant)],
        [],
      ),
    'updateUser' : IDL.Func(
        [UserId, IDL.Text, IDL.Text, Role, UserStatus],
        [IDL.Opt(User)],
        [],
      ),
    'updateVoiceCampaign' : IDL.Func(
        [
          CampaignId,
          IDL.Text,
          CampaignStatus,
          AudienceSegment,
          LeadStatus,
          VoiceAgentConfig,
        ],
        [IDL.Opt(VoiceCampaign)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };