/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiInteraction {
  'id' : InteractionId,
  'interactionType' : InteractionType,
  'minutesSaved' : bigint,
  'createdAt' : Timestamp,
  'agentId' : [] | [UserId],
  'tenantId' : TenantId,
  'summary' : string,
  'leadId' : LeadId,
  'durationSeconds' : bigint,
  'outcome' : InteractionOutcome,
  'voiceCall' : [] | [VoiceCallDetail],
}
export type AudienceSegment = { 'aiContacted' : null } |
  { 'liveTransferred' : null } |
  { 'sold' : null } |
  { 'allLeads' : null } |
  { 'newLeads' : null } |
  { 'apptBooked' : null };
export interface Billing {
  'id' : BillingId,
  'includedMinutes' : bigint,
  'invoiceHistory' : Array<InvoiceRecord>,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'planTier' : PlanTier,
  'usedMinutes' : bigint,
}
export type BillingId = bigint;
export interface BulkImportResult {
  'errors' : Array<string>,
  'createdIds' : Array<bigint>,
}
export interface BulkLeadInput {
  'status' : [] | [LeadStatus],
  'source' : [] | [LeadSource],
  'name' : string,
  'assignedAgentId' : [] | [UserId],
  'email' : [] | [string],
  'annualPremiumValue' : [] | [bigint],
  'phone' : string,
}
export type CampaignId = bigint;
export type CampaignStatus = { 'scheduled' : null } |
  { 'completed' : null } |
  { 'draft' : null } |
  { 'running' : null } |
  { 'archived' : null } |
  { 'paused' : null };
export interface ColumnChartMetric {
  'callsAi' : bigint,
  'apptsBooked' : bigint,
  'liveTransfers' : bigint,
  'smsSent' : bigint,
  'leadsSold' : bigint,
}
export interface DashboardSummary {
  'activeAgentsOnline' : bigint,
  'totalAgents' : bigint,
  'timeSavedByAiMinutes' : bigint,
  'totalLeads' : bigint,
  'activeAgentsPercentage' : number,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type InteractionId = bigint;
export type InteractionOutcome = { 'noAnswer' : null } |
  { 'sent' : null } |
  { 'booked' : null } |
  { 'transferred' : null } |
  { 'replied' : null } |
  { 'delivered' : null } |
  { 'failed' : null } |
  { 'qualified' : null };
export type InteractionType = { 'liveTransfer' : null } |
  { 'appointmentBooking' : null } |
  { 'textMessage' : null } |
  { 'voiceCall' : null };
export interface InvoiceRecord {
  'paid' : boolean,
  'invoiceId' : bigint,
  'issuedAt' : Timestamp,
  'amount' : bigint,
}
export interface Lead {
  'id' : LeadId,
  'status' : LeadStatus,
  'source' : LeadSource,
  'name' : string,
  'createdAt' : Timestamp,
  'assignedAgentId' : [] | [UserId],
  'email' : string,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'annualPremiumValue' : bigint,
  'phone' : string,
}
export type LeadId = bigint;
export type LeadSource = { 'referral' : null } |
  { 'voiceCampaign' : null } |
  { 'webForm' : null } |
  { 'smsCampaign' : null } |
  { 'aiDialer' : null } |
  { 'csvImport' : null } |
  { 'inbound' : null } |
  { 'outbound' : null };
export type LeadStatus = { 'aiContacted' : null } |
  { 'liveTransferred' : null } |
  { 'sold' : null } |
  { 'apptBooked' : null } |
  { 'newLead' : null };
export interface LiveEvent {
  'id' : bigint,
  'source' : LiveEventSource,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'message' : string,
}
export type LiveEventSource = { 'sys' : null } |
  { 'aiVoiceRouter' : null } |
  { 'voiceCampaign' : null } |
  { 'aiTextSetter' : null } |
  { 'smsCampaign' : null } |
  { 'aiDialer' : null };
export type PlanTier = { 'growth' : null } |
  { 'enterprise' : null } |
  { 'starter' : null } |
  { 'scale' : null };
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Role = { 'manager' : null } |
  { 'admin' : null } |
  { 'agent' : null };
export interface SmsCampaign {
  'id' : CampaignId,
  'status' : CampaignStatus,
  'messageTemplate' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'sentCount' : bigint,
  'tenantId' : TenantId,
  'audienceSegment' : AudienceSegment,
  'responseCount' : bigint,
}
export interface Tenant {
  'id' : TenantId,
  'createdAt' : Timestamp,
  'agencyName' : string,
  'voiceAgent' : VoiceAgentConfig,
  'primaryContact' : string,
  'planTier' : PlanTier,
}
export type TenantId = bigint;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface User {
  'id' : UserId,
  'status' : UserStatus,
  'principal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'tenantId' : TenantId,
}
export type UserId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'away' : null } |
  { 'offline' : null } |
  { 'online' : null };
export interface VoiceAgentConfig {
  'model' : string,
  'voiceProvider' : string,
  'voiceId' : string,
  'agentName' : string,
  'language' : string,
  'voiceSettings' : string,
  'apiKey' : string,
  'transferPhoneNumber' : string,
}
export interface VoiceCallDetail {
  'status' : VoiceCallStatus,
  'duration' : bigint,
  'callId' : string,
}
export interface VoiceCallRequest {
  'voiceId' : string,
  'task' : string,
  'tenantId' : TenantId,
  'language' : string,
  'leadId' : LeadId,
  'transferPhoneNumber' : string,
}
export interface VoiceCallResult {
  'status' : { 'initiated' : null } |
    { 'failed' : null },
  'error' : [] | [string],
  'callId' : string,
}
export type VoiceCallStatus = { 'initiated' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface VoiceCampaign {
  'id' : CampaignId,
  'status' : CampaignStatus,
  'minutesSaved' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'voiceAgent' : VoiceAgentConfig,
  'qualifiedTransfers' : bigint,
  'targetStatus' : LeadStatus,
  'targetSegment' : AudienceSegment,
  'callsPlaced' : bigint,
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__state' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addInvoice' : ActorMethod<[TenantId, bigint], [] | [Billing]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkImportLeads' : ActorMethod<
    [TenantId, Array<BulkLeadInput>],
    BulkImportResult
  >,
  'createAiInteraction' : ActorMethod<
    [
      TenantId,
      LeadId,
      [] | [UserId],
      InteractionType,
      InteractionOutcome,
      bigint,
      string,
    ],
    AiInteraction
  >,
  'createLead' : ActorMethod<
    [TenantId, string, string, string, LeadSource, bigint, [] | [UserId]],
    Lead
  >,
  'createSmsCampaign' : ActorMethod<
    [TenantId, string, AudienceSegment, string],
    SmsCampaign
  >,
  'createTenant' : ActorMethod<[string, string, PlanTier], Tenant>,
  'createUser' : ActorMethod<[TenantId, Principal, string, string, Role], User>,
  'createVoiceCampaign' : ActorMethod<
    [TenantId, string, AudienceSegment, LeadStatus, VoiceAgentConfig],
    VoiceCampaign
  >,
  'deleteAiInteraction' : ActorMethod<[InteractionId], boolean>,
  'deleteLead' : ActorMethod<[LeadId], boolean>,
  'deleteSmsCampaign' : ActorMethod<[CampaignId], boolean>,
  'deleteTenant' : ActorMethod<[TenantId], boolean>,
  'deleteUser' : ActorMethod<[UserId], boolean>,
  'deleteVoiceCampaign' : ActorMethod<[CampaignId], boolean>,
  'getAiInteraction' : ActorMethod<[InteractionId], [] | [AiInteraction]>,
  'getBilling' : ActorMethod<[TenantId], [] | [Billing]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getColumnChartMetrics' : ActorMethod<[TenantId], ColumnChartMetric>,
  'getDashboardSummary' : ActorMethod<[TenantId], DashboardSummary>,
  'getLead' : ActorMethod<[LeadId], [] | [Lead]>,
  'getLiveEventStream' : ActorMethod<[TenantId, bigint], Array<LiveEvent>>,
  'getSmsCampaign' : ActorMethod<[CampaignId], [] | [SmsCampaign]>,
  'getTenant' : ActorMethod<[TenantId], [] | [Tenant]>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'getVoiceCampaign' : ActorMethod<[CampaignId], [] | [VoiceCampaign]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'launchVoiceCampaign' : ActorMethod<
    [TenantId, CampaignId],
    Array<VoiceCallResult>
  >,
  'listAiInteractionsByLead' : ActorMethod<[LeadId], Array<AiInteraction>>,
  'listAiInteractionsByTenant' : ActorMethod<[TenantId], Array<AiInteraction>>,
  'listLeadsByStatus' : ActorMethod<[TenantId, LeadStatus], Array<Lead>>,
  'listLeadsByTenant' : ActorMethod<[TenantId], Array<Lead>>,
  'listSmsCampaignsByTenant' : ActorMethod<[TenantId], Array<SmsCampaign>>,
  'listTenants' : ActorMethod<[], Array<Tenant>>,
  'listUsersByTenant' : ActorMethod<[TenantId], Array<User>>,
  'listVoiceCampaignsByTenant' : ActorMethod<[TenantId], Array<VoiceCampaign>>,
  'placeVoiceCall' : ActorMethod<[VoiceCallRequest], VoiceCallResult>,
  'recordBillingUsage' : ActorMethod<[TenantId, bigint], [] | [Billing]>,
  'seedMockData' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAiInteraction' : ActorMethod<
    [InteractionId, InteractionOutcome, bigint, string],
    [] | [AiInteraction]
  >,
  'updateBillingPlan' : ActorMethod<
    [TenantId, PlanTier, bigint],
    [] | [Billing]
  >,
  'updateLead' : ActorMethod<
    [
      LeadId,
      string,
      string,
      string,
      LeadSource,
      bigint,
      LeadStatus,
      [] | [UserId],
    ],
    [] | [Lead]
  >,
  'updateSmsCampaign' : ActorMethod<
    [CampaignId, string, CampaignStatus, AudienceSegment, string],
    [] | [SmsCampaign]
  >,
  'updateTenant' : ActorMethod<
    [TenantId, string, string, PlanTier, VoiceAgentConfig],
    [] | [Tenant]
  >,
  'updateUser' : ActorMethod<
    [UserId, string, string, Role, UserStatus],
    [] | [User]
  >,
  'updateVoiceCampaign' : ActorMethod<
    [
      CampaignId,
      string,
      CampaignStatus,
      AudienceSegment,
      LeadStatus,
      VoiceAgentConfig,
    ],
    [] | [VoiceCampaign]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];