/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface VoiceCallDetail {
    status: VoiceCallStatus;
    duration: bigint;
    callId: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface Tenant {
    id: TenantId;
    createdAt: Timestamp;
    agencyName: string;
    voiceAgent: VoiceAgentConfig;
    primaryContact: string;
    planTier: PlanTier;
}
export type LeadId = bigint;
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface Lead {
    id: LeadId;
    status: LeadStatus;
    source: LeadSource;
    name: string;
    createdAt: Timestamp;
    assignedAgentId?: UserId;
    email: string;
    tenantId: TenantId;
    updatedAt: Timestamp;
    annualPremiumValue: bigint;
    phone: string;
}
export interface InvoiceRecord {
    paid: boolean;
    invoiceId: bigint;
    issuedAt: Timestamp;
    amount: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface VoiceCallResult {
    status: Variant_initiated_failed;
    error?: string;
    callId: string;
}
export interface LiveEvent {
    id: bigint;
    source: LiveEventSource;
    createdAt: Timestamp;
    tenantId: TenantId;
    message: string;
}
export interface AiInteraction {
    id: InteractionId;
    interactionType: InteractionType;
    minutesSaved: bigint;
    createdAt: Timestamp;
    agentId?: UserId;
    tenantId: TenantId;
    summary: string;
    leadId: LeadId;
    durationSeconds: bigint;
    outcome: InteractionOutcome;
    voiceCall?: VoiceCallDetail;
}
export type TenantId = bigint;
export interface VoiceCampaign {
    id: CampaignId;
    status: CampaignStatus;
    minutesSaved: bigint;
    name: string;
    createdAt: Timestamp;
    tenantId: TenantId;
    voiceAgent: VoiceAgentConfig;
    qualifiedTransfers: bigint;
    targetStatus: LeadStatus;
    targetSegment: AudienceSegment;
    callsPlaced: bigint;
}
export interface User {
    id: UserId;
    status: UserStatus;
    principal: Principal;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    tenantId: TenantId;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface ColumnChartMetric {
    callsAi: bigint;
    apptsBooked: bigint;
    liveTransfers: bigint;
    smsSent: bigint;
    leadsSold: bigint;
}
export interface DashboardSummary {
    activeAgentsOnline: bigint;
    totalAgents: bigint;
    timeSavedByAiMinutes: bigint;
    totalLeads: bigint;
    activeAgentsPercentage: number;
}
export type CampaignId = bigint;
export interface SmsCampaign {
    id: CampaignId;
    status: CampaignStatus;
    messageTemplate: string;
    name: string;
    createdAt: Timestamp;
    sentCount: bigint;
    tenantId: TenantId;
    audienceSegment: AudienceSegment;
    responseCount: bigint;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface VoiceAgentConfig {
    model: string;
    voiceProvider: string;
    voiceId: string;
    agentName: string;
    language: string;
    voiceSettings: string;
    apiKey: string;
    transferPhoneNumber: string;
}
export type UserId = bigint;
export type InteractionId = bigint;
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface BulkLeadInput {
    status?: LeadStatus;
    source?: LeadSource;
    name: string;
    assignedAgentId?: UserId;
    email?: string;
    annualPremiumValue?: bigint;
    phone: string;
}
export interface BulkImportResult {
    errors: Array<string>;
    createdIds: Array<bigint>;
}
export interface VoiceCallRequest {
    voiceId: string;
    task: string;
    tenantId: TenantId;
    language: string;
    leadId: LeadId;
    transferPhoneNumber: string;
}
export type BillingId = bigint;
export interface Billing {
    id: BillingId;
    includedMinutes: bigint;
    invoiceHistory: Array<InvoiceRecord>;
    tenantId: TenantId;
    updatedAt: Timestamp;
    planTier: PlanTier;
    usedMinutes: bigint;
}
export enum AudienceSegment {
    aiContacted = "aiContacted",
    liveTransferred = "liveTransferred",
    sold = "sold",
    allLeads = "allLeads",
    newLeads = "newLeads",
    apptBooked = "apptBooked"
}
export enum CampaignStatus {
    scheduled = "scheduled",
    completed = "completed",
    draft = "draft",
    running = "running",
    archived = "archived",
    paused = "paused"
}
export enum InteractionOutcome {
    noAnswer = "noAnswer",
    sent = "sent",
    booked = "booked",
    transferred = "transferred",
    replied = "replied",
    delivered = "delivered",
    failed = "failed",
    qualified = "qualified"
}
export enum InteractionType {
    liveTransfer = "liveTransfer",
    appointmentBooking = "appointmentBooking",
    textMessage = "textMessage",
    voiceCall = "voiceCall"
}
export enum LeadSource {
    referral = "referral",
    voiceCampaign = "voiceCampaign",
    webForm = "webForm",
    smsCampaign = "smsCampaign",
    aiDialer = "aiDialer",
    csvImport = "csvImport",
    inbound = "inbound",
    outbound = "outbound"
}
export enum LeadStatus {
    aiContacted = "aiContacted",
    liveTransferred = "liveTransferred",
    sold = "sold",
    apptBooked = "apptBooked",
    newLead = "newLead"
}
export enum LiveEventSource {
    sys = "sys",
    aiVoiceRouter = "aiVoiceRouter",
    voiceCampaign = "voiceCampaign",
    aiTextSetter = "aiTextSetter",
    smsCampaign = "smsCampaign",
    aiDialer = "aiDialer"
}
export enum PlanTier {
    growth = "growth",
    enterprise = "enterprise",
    starter = "starter",
    scale = "scale"
}
export enum Role {
    manager = "manager",
    admin = "admin",
    agent = "agent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    away = "away",
    offline = "offline",
    online = "online"
}
export enum Variant_initiated_failed {
    initiated = "initiated",
    failed = "failed"
}
export enum VoiceCallStatus {
    initiated = "initiated",
    completed = "completed",
    failed = "failed"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __state(): Promise<any>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addInvoice(tenantId: TenantId, amount: bigint): Promise<Billing | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkImportLeads(tenantId: TenantId, inputs: Array<BulkLeadInput>): Promise<BulkImportResult>;
    createAiInteraction(tenantId: TenantId, leadId: LeadId, agentId: UserId | null, interactionType: InteractionType, outcome: InteractionOutcome, durationSeconds: bigint, summary: string): Promise<AiInteraction>;
    createLead(tenantId: TenantId, name: string, phone: string, email: string, source: LeadSource, annualPremiumValue: bigint, assignedAgentId: UserId | null): Promise<Lead>;
    createSmsCampaign(tenantId: TenantId, name: string, audienceSegment: AudienceSegment, messageTemplate: string): Promise<SmsCampaign>;
    createTenant(agencyName: string, primaryContact: string, planTier: PlanTier): Promise<Tenant>;
    createUser(tenantId: TenantId, principal: Principal, name: string, email: string, role: Role): Promise<User>;
    createVoiceCampaign(tenantId: TenantId, name: string, targetSegment: AudienceSegment, targetStatus: LeadStatus, voiceAgent: VoiceAgentConfig): Promise<VoiceCampaign>;
    deleteAiInteraction(id: InteractionId): Promise<boolean>;
    deleteLead(id: LeadId): Promise<boolean>;
    deleteSmsCampaign(id: CampaignId): Promise<boolean>;
    deleteTenant(id: TenantId): Promise<boolean>;
    deleteUser(id: UserId): Promise<boolean>;
    deleteVoiceCampaign(id: CampaignId): Promise<boolean>;
    getAiInteraction(id: InteractionId): Promise<AiInteraction | null>;
    getBilling(tenantId: TenantId): Promise<Billing | null>;
    getCallerUserRole(): Promise<UserRole>;
    getColumnChartMetrics(tenantId: TenantId): Promise<ColumnChartMetric>;
    getDashboardSummary(tenantId: TenantId): Promise<DashboardSummary>;
    getLead(id: LeadId): Promise<Lead | null>;
    getLiveEventStream(tenantId: TenantId, limit: bigint): Promise<Array<LiveEvent>>;
    getSmsCampaign(id: CampaignId): Promise<SmsCampaign | null>;
    getTenant(id: TenantId): Promise<Tenant | null>;
    getUser(id: UserId): Promise<User | null>;
    getVoiceCampaign(id: CampaignId): Promise<VoiceCampaign | null>;
    isCallerAdmin(): Promise<boolean>;
    launchVoiceCampaign(tenantId: TenantId, campaignId: CampaignId): Promise<Array<VoiceCallResult>>;
    listAiInteractionsByLead(leadId: LeadId): Promise<Array<AiInteraction>>;
    listAiInteractionsByTenant(tenantId: TenantId): Promise<Array<AiInteraction>>;
    listLeadsByStatus(tenantId: TenantId, status: LeadStatus): Promise<Array<Lead>>;
    listLeadsByTenant(tenantId: TenantId): Promise<Array<Lead>>;
    listSmsCampaignsByTenant(tenantId: TenantId): Promise<Array<SmsCampaign>>;
    listTenants(): Promise<Array<Tenant>>;
    listUsersByTenant(tenantId: TenantId): Promise<Array<User>>;
    listVoiceCampaignsByTenant(tenantId: TenantId): Promise<Array<VoiceCampaign>>;
    placeVoiceCall(request: VoiceCallRequest): Promise<VoiceCallResult>;
    recordBillingUsage(tenantId: TenantId, usedMinutesDelta: bigint): Promise<Billing | null>;
    seedMockData(): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAiInteraction(id: InteractionId, outcome: InteractionOutcome, durationSeconds: bigint, summary: string): Promise<AiInteraction | null>;
    updateBillingPlan(tenantId: TenantId, planTier: PlanTier, includedMinutes: bigint): Promise<Billing | null>;
    updateLead(id: LeadId, name: string, phone: string, email: string, source: LeadSource, annualPremiumValue: bigint, status: LeadStatus, assignedAgentId: UserId | null): Promise<Lead | null>;
    updateSmsCampaign(id: CampaignId, name: string, status: CampaignStatus, audienceSegment: AudienceSegment, messageTemplate: string): Promise<SmsCampaign | null>;
    updateTenant(id: TenantId, agencyName: string, primaryContact: string, planTier: PlanTier, voiceAgent: VoiceAgentConfig): Promise<Tenant | null>;
    updateUser(id: UserId, name: string, email: string, role: Role, status: UserStatus): Promise<User | null>;
    updateVoiceCampaign(id: CampaignId, name: string, status: CampaignStatus, targetSegment: AudienceSegment, targetStatus: LeadStatus, voiceAgent: VoiceAgentConfig): Promise<VoiceCampaign | null>;
}
import type { AiInteraction as _AiInteraction, AudienceSegment as _AudienceSegment, Billing as _Billing, BillingId as _BillingId, BulkLeadInput as _BulkLeadInput, CampaignId as _CampaignId, CampaignStatus as _CampaignStatus, Error as _Error, InteractionId as _InteractionId, InteractionOutcome as _InteractionOutcome, InteractionType as _InteractionType, InvoiceRecord as _InvoiceRecord, Lead as _Lead, LeadId as _LeadId, LeadSource as _LeadSource, LeadStatus as _LeadStatus, LiveEvent as _LiveEvent, LiveEventSource as _LiveEventSource, PlanTier as _PlanTier, Result as _Result, Role as _Role, SmsCampaign as _SmsCampaign, Tenant as _Tenant, TenantId as _TenantId, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole, UserStatus as _UserStatus, VoiceAgentConfig as _VoiceAgentConfig, VoiceCallDetail as _VoiceCallDetail, VoiceCallResult as _VoiceCallResult, VoiceCallStatus as _VoiceCallStatus, VoiceCampaign as _VoiceCampaign } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __state(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__state();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__state();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addInvoice(arg0: TenantId, arg1: bigint): Promise<Billing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvoice(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvoice(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkImportLeads(arg0: TenantId, arg1: Array<BulkLeadInput>): Promise<BulkImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportLeads(arg0, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportLeads(arg0, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAiInteraction(arg0: TenantId, arg1: LeadId, arg2: UserId | null, arg3: InteractionType, arg4: InteractionOutcome, arg5: bigint, arg6: string): Promise<AiInteraction> {
        if (this.processError) {
            try {
                const result = await this.actor.createAiInteraction(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_InteractionType_n20(this._uploadFile, this._downloadFile, arg3), to_candid_InteractionOutcome_n22(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return from_candid_AiInteraction_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAiInteraction(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_InteractionType_n20(this._uploadFile, this._downloadFile, arg3), to_candid_InteractionOutcome_n22(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return from_candid_AiInteraction_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLead(arg0: TenantId, arg1: string, arg2: string, arg3: string, arg4: LeadSource, arg5: bigint, arg6: UserId | null): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0, arg1, arg2, arg3, to_candid_LeadSource_n17(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Lead_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0, arg1, arg2, arg3, to_candid_LeadSource_n17(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Lead_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSmsCampaign(arg0: TenantId, arg1: string, arg2: AudienceSegment, arg3: string): Promise<SmsCampaign> {
        if (this.processError) {
            try {
                const result = await this.actor.createSmsCampaign(arg0, arg1, to_candid_AudienceSegment_n42(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_SmsCampaign_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSmsCampaign(arg0, arg1, to_candid_AudienceSegment_n42(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_SmsCampaign_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTenant(arg0: string, arg1: string, arg2: PlanTier): Promise<Tenant> {
        if (this.processError) {
            try {
                const result = await this.actor.createTenant(arg0, arg1, to_candid_PlanTier_n50(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Tenant_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTenant(arg0, arg1, to_candid_PlanTier_n50(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Tenant_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: TenantId, arg1: Principal, arg2: string, arg3: string, arg4: Role): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2, arg3, to_candid_Role_n54(this._uploadFile, this._downloadFile, arg4));
                return from_candid_User_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2, arg3, to_candid_Role_n54(this._uploadFile, this._downloadFile, arg4));
            return from_candid_User_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVoiceCampaign(arg0: TenantId, arg1: string, arg2: AudienceSegment, arg3: LeadStatus, arg4: VoiceAgentConfig): Promise<VoiceCampaign> {
        if (this.processError) {
            try {
                const result = await this.actor.createVoiceCampaign(arg0, arg1, to_candid_AudienceSegment_n42(this._uploadFile, this._downloadFile, arg2), to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_VoiceCampaign_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVoiceCampaign(arg0, arg1, to_candid_AudienceSegment_n42(this._uploadFile, this._downloadFile, arg2), to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_VoiceCampaign_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAiInteraction(arg0: InteractionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAiInteraction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAiInteraction(arg0);
            return result;
        }
    }
    async deleteLead(arg0: LeadId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteSmsCampaign(arg0: CampaignId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSmsCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSmsCampaign(arg0);
            return result;
        }
    }
    async deleteTenant(arg0: TenantId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTenant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTenant(arg0);
            return result;
        }
    }
    async deleteUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async deleteVoiceCampaign(arg0: CampaignId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVoiceCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVoiceCampaign(arg0);
            return result;
        }
    }
    async getAiInteraction(arg0: InteractionId): Promise<AiInteraction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAiInteraction(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAiInteraction(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBilling(arg0: TenantId): Promise<Billing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBilling(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBilling(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getColumnChartMetrics(arg0: TenantId): Promise<ColumnChartMetric> {
        if (this.processError) {
            try {
                const result = await this.actor.getColumnChartMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColumnChartMetrics(arg0);
            return result;
        }
    }
    async getDashboardSummary(arg0: TenantId): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary(arg0);
            return result;
        }
    }
    async getLead(arg0: LeadId): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiveEventStream(arg0: TenantId, arg1: bigint): Promise<Array<LiveEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveEventStream(arg0, arg1);
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveEventStream(arg0, arg1);
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmsCampaign(arg0: CampaignId): Promise<SmsCampaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmsCampaign(arg0);
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmsCampaign(arg0);
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTenant(arg0: TenantId): Promise<Tenant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTenant(arg0);
                return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTenant(arg0);
            return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoiceCampaign(arg0: CampaignId): Promise<VoiceCampaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceCampaign(arg0);
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceCampaign(arg0);
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async launchVoiceCampaign(arg0: TenantId, arg1: CampaignId): Promise<Array<VoiceCallResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.launchVoiceCampaign(arg0, arg1);
                return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.launchVoiceCampaign(arg0, arg1);
            return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAiInteractionsByLead(arg0: LeadId): Promise<Array<AiInteraction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAiInteractionsByLead(arg0);
                return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAiInteractionsByLead(arg0);
            return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAiInteractionsByTenant(arg0: TenantId): Promise<Array<AiInteraction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAiInteractionsByTenant(arg0);
                return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAiInteractionsByTenant(arg0);
            return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLeadsByStatus(arg0: TenantId, arg1: LeadStatus): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeadsByStatus(arg0, to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeadsByStatus(arg0, to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLeadsByTenant(arg0: TenantId): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeadsByTenant(arg0);
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeadsByTenant(arg0);
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSmsCampaignsByTenant(arg0: TenantId): Promise<Array<SmsCampaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSmsCampaignsByTenant(arg0);
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSmsCampaignsByTenant(arg0);
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTenants(): Promise<Array<Tenant>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTenants();
                return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTenants();
            return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsersByTenant(arg0: TenantId): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsersByTenant(arg0);
                return from_candid_vec_n86(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsersByTenant(arg0);
            return from_candid_vec_n86(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVoiceCampaignsByTenant(arg0: TenantId): Promise<Array<VoiceCampaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVoiceCampaignsByTenant(arg0);
                return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVoiceCampaignsByTenant(arg0);
            return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeVoiceCall(arg0: VoiceCallRequest): Promise<VoiceCallResult> {
        if (this.processError) {
            try {
                const result = await this.actor.placeVoiceCall(arg0);
                return from_candid_VoiceCallResult_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeVoiceCall(arg0);
            return from_candid_VoiceCallResult_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordBillingUsage(arg0: TenantId, arg1: bigint): Promise<Billing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBillingUsage(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBillingUsage(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedMockData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedMockData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedMockData();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAiInteraction(arg0: InteractionId, arg1: InteractionOutcome, arg2: bigint, arg3: string): Promise<AiInteraction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAiInteraction(arg0, to_candid_InteractionOutcome_n22(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAiInteraction(arg0, to_candid_InteractionOutcome_n22(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBillingPlan(arg0: TenantId, arg1: PlanTier, arg2: bigint): Promise<Billing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBillingPlan(arg0, to_candid_PlanTier_n50(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBillingPlan(arg0, to_candid_PlanTier_n50(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLead(arg0: LeadId, arg1: string, arg2: string, arg3: string, arg4: LeadSource, arg5: bigint, arg6: LeadStatus, arg7: UserId | null): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, to_candid_LeadSource_n17(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg7));
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, to_candid_LeadSource_n17(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg7));
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSmsCampaign(arg0: CampaignId, arg1: string, arg2: CampaignStatus, arg3: AudienceSegment, arg4: string): Promise<SmsCampaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSmsCampaign(arg0, arg1, to_candid_CampaignStatus_n88(this._uploadFile, this._downloadFile, arg2), to_candid_AudienceSegment_n42(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSmsCampaign(arg0, arg1, to_candid_CampaignStatus_n88(this._uploadFile, this._downloadFile, arg2), to_candid_AudienceSegment_n42(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTenant(arg0: TenantId, arg1: string, arg2: string, arg3: PlanTier, arg4: VoiceAgentConfig): Promise<Tenant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTenant(arg0, arg1, arg2, to_candid_PlanTier_n50(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTenant(arg0, arg1, arg2, to_candid_PlanTier_n50(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: UserId, arg1: string, arg2: string, arg3: Role, arg4: UserStatus): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_Role_n54(this._uploadFile, this._downloadFile, arg3), to_candid_UserStatus_n90(this._uploadFile, this._downloadFile, arg4));
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_Role_n54(this._uploadFile, this._downloadFile, arg3), to_candid_UserStatus_n90(this._uploadFile, this._downloadFile, arg4));
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVoiceCampaign(arg0: CampaignId, arg1: string, arg2: CampaignStatus, arg3: AudienceSegment, arg4: LeadStatus, arg5: VoiceAgentConfig): Promise<VoiceCampaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVoiceCampaign(arg0, arg1, to_candid_CampaignStatus_n88(this._uploadFile, this._downloadFile, arg2), to_candid_AudienceSegment_n42(this._uploadFile, this._downloadFile, arg3), to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVoiceCampaign(arg0, arg1, to_candid_CampaignStatus_n88(this._uploadFile, this._downloadFile, arg2), to_candid_AudienceSegment_n42(this._uploadFile, this._downloadFile, arg3), to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AiInteraction_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AiInteraction): AiInteraction {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_AudienceSegment_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudienceSegment): AudienceSegment {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Billing_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Billing): Billing {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_CampaignStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignStatus): CampaignStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_InteractionOutcome_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InteractionOutcome): InteractionOutcome {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_InteractionType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InteractionType): InteractionType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_LeadSource_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadSource): LeadSource {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_LiveEventSource_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveEventSource): LiveEventSource {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_LiveEvent_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveEvent): LiveEvent {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_PlanTier_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanTier): PlanTier {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_SmsCampaign_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SmsCampaign): SmsCampaign {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Tenant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tenant): Tenant {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_User_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_VoiceCallDetail_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceCallDetail): VoiceCallDetail {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_VoiceCallResult_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceCallResult): VoiceCallResult {
    return from_candid_record_n79(_uploadFile, _downloadFile, value);
}
function from_candid_VoiceCallStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceCallStatus): VoiceCallStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_VoiceCampaign_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceCampaign): VoiceCampaign {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoiceCallDetail]): VoiceCallDetail | null {
    return value.length === 0 ? null : from_candid_VoiceCallDetail_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Billing]): Billing | null {
    return value.length === 0 ? null : from_candid_Billing_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AiInteraction]): AiInteraction | null {
    return value.length === 0 ? null : from_candid_AiInteraction_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : from_candid_Lead_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SmsCampaign]): SmsCampaign | null {
    return value.length === 0 ? null : from_candid_SmsCampaign_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tenant]): Tenant | null {
    return value.length === 0 ? null : from_candid_Tenant_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoiceCampaign]): VoiceCampaign | null {
    return value.length === 0 ? null : from_candid_VoiceCampaign_n62(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InteractionId;
    interactionType: _InteractionType;
    minutesSaved: bigint;
    createdAt: _Timestamp;
    agentId: [] | [_UserId];
    tenantId: _TenantId;
    summary: string;
    leadId: _LeadId;
    durationSeconds: bigint;
    outcome: _InteractionOutcome;
    voiceCall: [] | [_VoiceCallDetail];
}): {
    id: InteractionId;
    interactionType: InteractionType;
    minutesSaved: bigint;
    createdAt: Timestamp;
    agentId?: UserId;
    tenantId: TenantId;
    summary: string;
    leadId: LeadId;
    durationSeconds: bigint;
    outcome: InteractionOutcome;
    voiceCall?: VoiceCallDetail;
} {
    return {
        id: value.id,
        interactionType: from_candid_InteractionType_n26(_uploadFile, _downloadFile, value.interactionType),
        minutesSaved: value.minutesSaved,
        createdAt: value.createdAt,
        agentId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.agentId)),
        tenantId: value.tenantId,
        summary: value.summary,
        leadId: value.leadId,
        durationSeconds: value.durationSeconds,
        outcome: from_candid_InteractionOutcome_n29(_uploadFile, _downloadFile, value.outcome),
        voiceCall: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.voiceCall))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _VoiceCallStatus;
    duration: bigint;
    callId: string;
}): {
    status: VoiceCallStatus;
    duration: bigint;
    callId: string;
} {
    return {
        status: from_candid_VoiceCallStatus_n34(_uploadFile, _downloadFile, value.status),
        duration: value.duration,
        callId: value.callId
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LeadId;
    status: _LeadStatus;
    source: _LeadSource;
    name: string;
    createdAt: _Timestamp;
    assignedAgentId: [] | [_UserId];
    email: string;
    tenantId: _TenantId;
    updatedAt: _Timestamp;
    annualPremiumValue: bigint;
    phone: string;
}): {
    id: LeadId;
    status: LeadStatus;
    source: LeadSource;
    name: string;
    createdAt: Timestamp;
    assignedAgentId?: UserId;
    email: string;
    tenantId: TenantId;
    updatedAt: Timestamp;
    annualPremiumValue: bigint;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n38(_uploadFile, _downloadFile, value.status),
        source: from_candid_LeadSource_n40(_uploadFile, _downloadFile, value.source),
        name: value.name,
        createdAt: value.createdAt,
        assignedAgentId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.assignedAgentId)),
        email: value.email,
        tenantId: value.tenantId,
        updatedAt: value.updatedAt,
        annualPremiumValue: value.annualPremiumValue,
        phone: value.phone
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CampaignId;
    status: _CampaignStatus;
    messageTemplate: string;
    name: string;
    createdAt: _Timestamp;
    sentCount: bigint;
    tenantId: _TenantId;
    audienceSegment: _AudienceSegment;
    responseCount: bigint;
}): {
    id: CampaignId;
    status: CampaignStatus;
    messageTemplate: string;
    name: string;
    createdAt: Timestamp;
    sentCount: bigint;
    tenantId: TenantId;
    audienceSegment: AudienceSegment;
    responseCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CampaignStatus_n46(_uploadFile, _downloadFile, value.status),
        messageTemplate: value.messageTemplate,
        name: value.name,
        createdAt: value.createdAt,
        sentCount: value.sentCount,
        tenantId: value.tenantId,
        audienceSegment: from_candid_AudienceSegment_n48(_uploadFile, _downloadFile, value.audienceSegment),
        responseCount: value.responseCount
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TenantId;
    createdAt: _Timestamp;
    agencyName: string;
    voiceAgent: _VoiceAgentConfig;
    primaryContact: string;
    planTier: _PlanTier;
}): {
    id: TenantId;
    createdAt: Timestamp;
    agencyName: string;
    voiceAgent: VoiceAgentConfig;
    primaryContact: string;
    planTier: PlanTier;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        agencyName: value.agencyName,
        voiceAgent: value.voiceAgent,
        primaryContact: value.primaryContact,
        planTier: from_candid_PlanTier_n8(_uploadFile, _downloadFile, value.planTier)
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    principal: Principal;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    email: string;
    tenantId: _TenantId;
}): {
    id: UserId;
    status: UserStatus;
    principal: Principal;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    tenantId: TenantId;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n58(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n60(_uploadFile, _downloadFile, value.role),
        email: value.email,
        tenantId: value.tenantId
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CampaignId;
    status: _CampaignStatus;
    minutesSaved: bigint;
    name: string;
    createdAt: _Timestamp;
    tenantId: _TenantId;
    voiceAgent: _VoiceAgentConfig;
    qualifiedTransfers: bigint;
    targetStatus: _LeadStatus;
    targetSegment: _AudienceSegment;
    callsPlaced: bigint;
}): {
    id: CampaignId;
    status: CampaignStatus;
    minutesSaved: bigint;
    name: string;
    createdAt: Timestamp;
    tenantId: TenantId;
    voiceAgent: VoiceAgentConfig;
    qualifiedTransfers: bigint;
    targetStatus: LeadStatus;
    targetSegment: AudienceSegment;
    callsPlaced: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CampaignStatus_n46(_uploadFile, _downloadFile, value.status),
        minutesSaved: value.minutesSaved,
        name: value.name,
        createdAt: value.createdAt,
        tenantId: value.tenantId,
        voiceAgent: value.voiceAgent,
        qualifiedTransfers: value.qualifiedTransfers,
        targetStatus: from_candid_LeadStatus_n38(_uploadFile, _downloadFile, value.targetStatus),
        targetSegment: from_candid_AudienceSegment_n48(_uploadFile, _downloadFile, value.targetSegment),
        callsPlaced: value.callsPlaced
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BillingId;
    includedMinutes: bigint;
    invoiceHistory: Array<_InvoiceRecord>;
    tenantId: _TenantId;
    updatedAt: _Timestamp;
    planTier: _PlanTier;
    usedMinutes: bigint;
}): {
    id: BillingId;
    includedMinutes: bigint;
    invoiceHistory: Array<InvoiceRecord>;
    tenantId: TenantId;
    updatedAt: Timestamp;
    planTier: PlanTier;
    usedMinutes: bigint;
} {
    return {
        id: value.id,
        includedMinutes: value.includedMinutes,
        invoiceHistory: value.invoiceHistory,
        tenantId: value.tenantId,
        updatedAt: value.updatedAt,
        planTier: from_candid_PlanTier_n8(_uploadFile, _downloadFile, value.planTier),
        usedMinutes: value.usedMinutes
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    source: _LiveEventSource;
    createdAt: _Timestamp;
    tenantId: _TenantId;
    message: string;
}): {
    id: bigint;
    source: LiveEventSource;
    createdAt: Timestamp;
    tenantId: TenantId;
    message: string;
} {
    return {
        id: value.id,
        source: from_candid_LiveEventSource_n71(_uploadFile, _downloadFile, value.source),
        createdAt: value.createdAt,
        tenantId: value.tenantId,
        message: value.message
    };
}
function from_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        initiated: null;
    } | {
        failed: null;
    };
    error: [] | [string];
    callId: string;
}): {
    status: Variant_initiated_failed;
    error?: string;
    callId: string;
} {
    return {
        status: from_candid_variant_n80(_uploadFile, _downloadFile, value.status),
        error: record_opt_to_undefined(from_candid_opt_n81(_uploadFile, _downloadFile, value.error)),
        callId: value.callId
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    liveTransfer: null;
} | {
    appointmentBooking: null;
} | {
    textMessage: null;
} | {
    voiceCall: null;
}): InteractionType {
    return "liveTransfer" in value ? InteractionType.liveTransfer : "appointmentBooking" in value ? InteractionType.appointmentBooking : "textMessage" in value ? InteractionType.textMessage : "voiceCall" in value ? InteractionType.voiceCall : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    noAnswer: null;
} | {
    sent: null;
} | {
    booked: null;
} | {
    transferred: null;
} | {
    replied: null;
} | {
    delivered: null;
} | {
    failed: null;
} | {
    qualified: null;
}): InteractionOutcome {
    return "noAnswer" in value ? InteractionOutcome.noAnswer : "sent" in value ? InteractionOutcome.sent : "booked" in value ? InteractionOutcome.booked : "transferred" in value ? InteractionOutcome.transferred : "replied" in value ? InteractionOutcome.replied : "delivered" in value ? InteractionOutcome.delivered : "failed" in value ? InteractionOutcome.failed : "qualified" in value ? InteractionOutcome.qualified : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    initiated: null;
} | {
    completed: null;
} | {
    failed: null;
}): VoiceCallStatus {
    return "initiated" in value ? VoiceCallStatus.initiated : "completed" in value ? VoiceCallStatus.completed : "failed" in value ? VoiceCallStatus.failed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aiContacted: null;
} | {
    liveTransferred: null;
} | {
    sold: null;
} | {
    apptBooked: null;
} | {
    newLead: null;
}): LeadStatus {
    return "aiContacted" in value ? LeadStatus.aiContacted : "liveTransferred" in value ? LeadStatus.liveTransferred : "sold" in value ? LeadStatus.sold : "apptBooked" in value ? LeadStatus.apptBooked : "newLead" in value ? LeadStatus.newLead : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referral: null;
} | {
    voiceCampaign: null;
} | {
    webForm: null;
} | {
    smsCampaign: null;
} | {
    aiDialer: null;
} | {
    csvImport: null;
} | {
    inbound: null;
} | {
    outbound: null;
}): LeadSource {
    return "referral" in value ? LeadSource.referral : "voiceCampaign" in value ? LeadSource.voiceCampaign : "webForm" in value ? LeadSource.webForm : "smsCampaign" in value ? LeadSource.smsCampaign : "aiDialer" in value ? LeadSource.aiDialer : "csvImport" in value ? LeadSource.csvImport : "inbound" in value ? LeadSource.inbound : "outbound" in value ? LeadSource.outbound : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    completed: null;
} | {
    draft: null;
} | {
    running: null;
} | {
    archived: null;
} | {
    paused: null;
}): CampaignStatus {
    return "scheduled" in value ? CampaignStatus.scheduled : "completed" in value ? CampaignStatus.completed : "draft" in value ? CampaignStatus.draft : "running" in value ? CampaignStatus.running : "archived" in value ? CampaignStatus.archived : "paused" in value ? CampaignStatus.paused : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aiContacted: null;
} | {
    liveTransferred: null;
} | {
    sold: null;
} | {
    allLeads: null;
} | {
    newLeads: null;
} | {
    apptBooked: null;
}): AudienceSegment {
    return "aiContacted" in value ? AudienceSegment.aiContacted : "liveTransferred" in value ? AudienceSegment.liveTransferred : "sold" in value ? AudienceSegment.sold : "allLeads" in value ? AudienceSegment.allLeads : "newLeads" in value ? AudienceSegment.newLeads : "apptBooked" in value ? AudienceSegment.apptBooked : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    away: null;
} | {
    offline: null;
} | {
    online: null;
}): UserStatus {
    return "away" in value ? UserStatus.away : "offline" in value ? UserStatus.offline : "online" in value ? UserStatus.online : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    agent: null;
}): Role {
    return "manager" in value ? Role.manager : "admin" in value ? Role.admin : "agent" in value ? Role.agent : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sys: null;
} | {
    aiVoiceRouter: null;
} | {
    voiceCampaign: null;
} | {
    aiTextSetter: null;
} | {
    smsCampaign: null;
} | {
    aiDialer: null;
}): LiveEventSource {
    return "sys" in value ? LiveEventSource.sys : "aiVoiceRouter" in value ? LiveEventSource.aiVoiceRouter : "voiceCampaign" in value ? LiveEventSource.voiceCampaign : "aiTextSetter" in value ? LiveEventSource.aiTextSetter : "smsCampaign" in value ? LiveEventSource.smsCampaign : "aiDialer" in value ? LiveEventSource.aiDialer : value;
}
function from_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    initiated: null;
} | {
    failed: null;
}): Variant_initiated_failed {
    return "initiated" in value ? Variant_initiated_failed.initiated : "failed" in value ? Variant_initiated_failed.failed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    growth: null;
} | {
    enterprise: null;
} | {
    starter: null;
} | {
    scale: null;
}): PlanTier {
    return "growth" in value ? PlanTier.growth : "enterprise" in value ? PlanTier.enterprise : "starter" in value ? PlanTier.starter : "scale" in value ? PlanTier.scale : value;
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiveEvent>): Array<LiveEvent> {
    return value.map((x)=>from_candid_LiveEvent_n69(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VoiceCallResult>): Array<VoiceCallResult> {
    return value.map((x)=>from_candid_VoiceCallResult_n78(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AiInteraction>): Array<AiInteraction> {
    return value.map((x)=>from_candid_AiInteraction_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SmsCampaign>): Array<SmsCampaign> {
    return value.map((x)=>from_candid_SmsCampaign_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tenant>): Array<Tenant> {
    return value.map((x)=>from_candid_Tenant_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VoiceCampaign>): Array<VoiceCampaign> {
    return value.map((x)=>from_candid_VoiceCampaign_n62(_uploadFile, _downloadFile, x));
}
function to_candid_AudienceSegment_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudienceSegment): _AudienceSegment {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_BulkLeadInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BulkLeadInput): _BulkLeadInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_CampaignStatus_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignStatus): _CampaignStatus {
    return to_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function to_candid_InteractionOutcome_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionOutcome): _InteractionOutcome {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_InteractionType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionType): _InteractionType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_LeadSource_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadSource): _LeadSource {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_PlanTier_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanTier): _PlanTier {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n91(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: LeadStatus;
    source?: LeadSource;
    name: string;
    assignedAgentId?: UserId;
    email?: string;
    annualPremiumValue?: bigint;
    phone: string;
}): {
    status: [] | [_LeadStatus];
    source: [] | [_LeadSource];
    name: string;
    assignedAgentId: [] | [_UserId];
    email: [] | [string];
    annualPremiumValue: [] | [bigint];
    phone: string;
} {
    return {
        status: value.status ? candid_some(to_candid_LeadStatus_n15(_uploadFile, _downloadFile, value.status)) : candid_none(),
        source: value.source ? candid_some(to_candid_LeadSource_n17(_uploadFile, _downloadFile, value.source)) : candid_none(),
        name: value.name,
        assignedAgentId: value.assignedAgentId ? candid_some(value.assignedAgentId) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        annualPremiumValue: value.annualPremiumValue ? candid_some(value.annualPremiumValue) : candid_none(),
        phone: value.phone
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    aiContacted: null;
} | {
    liveTransferred: null;
} | {
    sold: null;
} | {
    apptBooked: null;
} | {
    newLead: null;
} {
    return value == LeadStatus.aiContacted ? {
        aiContacted: null
    } : value == LeadStatus.liveTransferred ? {
        liveTransferred: null
    } : value == LeadStatus.sold ? {
        sold: null
    } : value == LeadStatus.apptBooked ? {
        apptBooked: null
    } : value == LeadStatus.newLead ? {
        newLead: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadSource): {
    referral: null;
} | {
    voiceCampaign: null;
} | {
    webForm: null;
} | {
    smsCampaign: null;
} | {
    aiDialer: null;
} | {
    csvImport: null;
} | {
    inbound: null;
} | {
    outbound: null;
} {
    return value == LeadSource.referral ? {
        referral: null
    } : value == LeadSource.voiceCampaign ? {
        voiceCampaign: null
    } : value == LeadSource.webForm ? {
        webForm: null
    } : value == LeadSource.smsCampaign ? {
        smsCampaign: null
    } : value == LeadSource.aiDialer ? {
        aiDialer: null
    } : value == LeadSource.csvImport ? {
        csvImport: null
    } : value == LeadSource.inbound ? {
        inbound: null
    } : value == LeadSource.outbound ? {
        outbound: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionType): {
    liveTransfer: null;
} | {
    appointmentBooking: null;
} | {
    textMessage: null;
} | {
    voiceCall: null;
} {
    return value == InteractionType.liveTransfer ? {
        liveTransfer: null
    } : value == InteractionType.appointmentBooking ? {
        appointmentBooking: null
    } : value == InteractionType.textMessage ? {
        textMessage: null
    } : value == InteractionType.voiceCall ? {
        voiceCall: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionOutcome): {
    noAnswer: null;
} | {
    sent: null;
} | {
    booked: null;
} | {
    transferred: null;
} | {
    replied: null;
} | {
    delivered: null;
} | {
    failed: null;
} | {
    qualified: null;
} {
    return value == InteractionOutcome.noAnswer ? {
        noAnswer: null
    } : value == InteractionOutcome.sent ? {
        sent: null
    } : value == InteractionOutcome.booked ? {
        booked: null
    } : value == InteractionOutcome.transferred ? {
        transferred: null
    } : value == InteractionOutcome.replied ? {
        replied: null
    } : value == InteractionOutcome.delivered ? {
        delivered: null
    } : value == InteractionOutcome.failed ? {
        failed: null
    } : value == InteractionOutcome.qualified ? {
        qualified: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudienceSegment): {
    aiContacted: null;
} | {
    liveTransferred: null;
} | {
    sold: null;
} | {
    allLeads: null;
} | {
    newLeads: null;
} | {
    apptBooked: null;
} {
    return value == AudienceSegment.aiContacted ? {
        aiContacted: null
    } : value == AudienceSegment.liveTransferred ? {
        liveTransferred: null
    } : value == AudienceSegment.sold ? {
        sold: null
    } : value == AudienceSegment.allLeads ? {
        allLeads: null
    } : value == AudienceSegment.newLeads ? {
        newLeads: null
    } : value == AudienceSegment.apptBooked ? {
        apptBooked: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanTier): {
    growth: null;
} | {
    enterprise: null;
} | {
    starter: null;
} | {
    scale: null;
} {
    return value == PlanTier.growth ? {
        growth: null
    } : value == PlanTier.enterprise ? {
        enterprise: null
    } : value == PlanTier.starter ? {
        starter: null
    } : value == PlanTier.scale ? {
        scale: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    manager: null;
} | {
    admin: null;
} | {
    agent: null;
} {
    return value == Role.manager ? {
        manager: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.agent ? {
        agent: null
    } : value;
}
function to_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignStatus): {
    scheduled: null;
} | {
    completed: null;
} | {
    draft: null;
} | {
    running: null;
} | {
    archived: null;
} | {
    paused: null;
} {
    return value == CampaignStatus.scheduled ? {
        scheduled: null
    } : value == CampaignStatus.completed ? {
        completed: null
    } : value == CampaignStatus.draft ? {
        draft: null
    } : value == CampaignStatus.running ? {
        running: null
    } : value == CampaignStatus.archived ? {
        archived: null
    } : value == CampaignStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    away: null;
} | {
    offline: null;
} | {
    online: null;
} {
    return value == UserStatus.away ? {
        away: null
    } : value == UserStatus.offline ? {
        offline: null
    } : value == UserStatus.online ? {
        online: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BulkLeadInput>): Array<_BulkLeadInput> {
    return value.map((x)=>to_candid_BulkLeadInput_n13(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
